name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  install-and-test:
    name: Install, Type Check, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          cache: 'npm'

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgresql://user:password@localhost:5432/mydb" > .env
          echo "NEXTAUTH_SECRET=placeholder" >> .env
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env
          echo "GOOGLE_CLIENT_ID=placeholder" >> .env
          echo "GOOGLE_CLIENT_SECRET=placeholder" >> .env
          echo "GITHUB_CLIENT_ID=placeholder" >> .env
          echo "GITHUB_CLIENT_SECRET=placeholder" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type check
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: npm run build
